from tkinter import *

root = Tk()
root.title("Buttons")
root.geometry("300x300")
root.iconbitmap("assets/favicon.ico")
root.configure(bg="black")  
frame = Frame(root)
frame.pack()
button4 = Button(frame,text="Button 4",fg="white",bg="black")
button4.pack(side=LEFT)
button5 = Button(frame,text="Button 5",fg="orange")
button5.pack(side=RIGHT)
button1 = Button(frame,text="Button 1",fg="red")
button1.pack()
button2 = Button(frame,text="Button 2",fg="blue")
button2.pack()
button3 = Button(frame,text="Button 3",fg="green")
button3.pack()
mainloop()